### ISSUE TITLE
Curve Smoothing 

### ISSUE THREAD

**Issue by EmmaLiTsai** [EmmaLiTsai/recoverKBTDR#1]
- using loess fit to smooth the curve of the dive trace 
- using group_by() and summarize() to reduce dive trace to address an issue with edge detection 
- using derivatives to identify ascent/descent portions of a dive 

Taken on by: DWS 
Date: 12/15/2020

**Comment by dschwilk** [comment]
As I worked through this I realize that one difficulty is the doubled lines in the scan file.  I think that either:

1) the image processing prior to R should narrow to a single line or
2) (easier) we just use the raw pixel data without line detection (but need to ensure no stray pixels).

The problem is that, either with summarize to X first or LOESS smooth first, both have problems with very steep areas of the curve and will detect phantom wiggles within a single ascent or descent. In the test file, this is really only an issue on the first big ascent but I suspect it will be an ongoing problem. This could probably all be dealt with in "dive" cleaning following smoothin and derivative calculation, but I think it is an artifact of the doubled lines in the raw data. Do you have a version of the scan with just the pixels?  I suspect this will work better. Something about the resolution of the scan and the double  lines leads to these wiggles.

Illustrated below, method A is summarize first, method B is loess first.  There is no way to avoid the squiggles because any less tight smoothing with loess misses the fine real detail.

Method A: 
![smooth_method_a](https://user-images.githubusercontent.com/2388939/102254366-229f9180-3ece-11eb-9b37-7b38dc0ddf02.png)

Method B:
![smooth_method_b](https://user-images.githubusercontent.com/2388939/102254386-27644580-3ece-11eb-9779-416f42c9f597.png)

**Comment by dschwilk** [comment]
Good news! think spline smoothing can fix this and hopefully work with a variety of scan inputs.


Here is summarizing by x first, then smooth.spline. With raw data in gray for comparison.

![spline_method](https://user-images.githubusercontent.com/2388939/102256327-e15cb100-3ed0-11eb-9718-ea6f29f82b21.png)
